### PR TITLE
Fix the scoreboard calculations

### LINKED ISSUE #46: Scoreboard textual issue after 0 seconds.
scoreboard

### PR DESCRIPTION
**Pull request by Abbondanzo**
Fixes #46. Since we [fill in -100](https://github.com/SaltieRL/DistributedReplays/blob/5ecf61651d79912358c451f0a7e14d7ae2aa454e/backend/blueprints/spa_api/service_layers/replay/replay_positions.py#L45) when we don't have values for a frame, this breaks the calculation.

### CODE REVIEW

File: src/viewer/components/ScoreBoard.tsx [hunk 1]
```diff
@@ -49,9 +49,10 @@ export default class Scoreboard extends PureComponent<Props, State> {
     this.onFrame.cancel()
   }
 
-  getDateTimeString() {
-    const { gameTime } = this.state
-
+  getTimerString() {
+    let { gameTime } = this.state
+    // The frame is filled as -100 when the data is missing, so we set the minimum to 0
+    gameTime = gameTime < 0 ? 0 : gameTime
```
Comment (dtracers) [inline src/viewer/components/ScoreBoard.tsx]: how does this handle overtime?

Comment (Abbondanzo) [reply src/viewer/components/ScoreBoard.tsx]: Overtime is positive
